#!/bin/sh -e
# Wrapper for calling autoconf-generated ./configure scripts
. cpt-lib

set -- \
    "--prefix=$CPT_PKG_PREFIX" \
    "--sysconfdir=$CPT_PKG_ETCDIR" \
    "--bindir=$CPT_PKG_BINDIR" \
    "--sbindir=$CPT_PKG_SBINDIR" \
    "--mandir=$CPT_PKG_MANDIR" \
    "--infodir=$CPT_PKG_INFODIR" \
    "--localstatedir=$CPT_PKG_LOCALSTATEDIR" \
    "$@"


[ "$CPT_CROSS_TRIPLET" ] &&
    set -- "$@" \
        "--host=$CPT_CROSS_TRIPLET" \
        "--with-sysroot=$CPT_ROOT$CPT_PKG_PREFIX"

"${configure_file:-./configure}" "$@"
