.Dd Feb 25, 2021
.Dt cpt-build 1
.Sh NAME
.Nm cpt-build
.Nd build given packages
.Sh SYNOPSIS
.Nm cpt-build
.Op Fl tfy
.Op Fl -root Ar ROOT
.Op Fl hv
.Op Ar package...
.Sh DESCRIPTION
cpt-build will build given packages and their dependencies. If multiple packages
are specified, it will ask to install the packages as well.
.Pp
The options are as follows:
.Bl -tag -width 13n
.It Fl t , -test
Run tests (if they exist)
.It Fl f , -force
Force operation
.It Fl y , -no-prompt
Do not prompt for confirmation
.It Fl -root Ar CPT_ROOT
Use an alternate root directory
.It Fl h , -help
Show help message
.It Fl v , -version
Print version information
.El
.Sh AUTHOR
.An Cem Keylan Aq Mt cem@ckyln.com
.Sh LICENSE
See LICENSE for copyright information.
.Sh SEE ALSO
.Xr cpt 1
.Xr cpt-install 1
