.TH "cpt-search" "1" "2020-07-24" "CARBS LINUX" "General Commands Manual"
.SH NAME
cpt-search
.SH SYNOPSIS
\fBcpt-search\fR [--single] [pkg...]

.SH DESCRIPTION
cpt-search can be used to search packages. Glob characters can be used in the
search. If the \fI--single\fR option is specified cpt-search will only output
the first match.

.SH LICENSE
See LICENSE for copyright information.
.SH SEE ALSO
cpt(1)
