.TH "cpt-install" "1" "2020-07-24" "CARBS LINUX" "General Commands Manual"
.SH NAME
cpt-install
.SH SYNOPSIS
\fBcpt-install\fR [options] [pkg...]

.SH OPTIONS
.TP
\fB--force\fR           Force installation
.TP
\fB--root\fR [rootdir]  Use an alternate root directory
.PP

.SH DESCRIPTION
cpt-install installs the given packages.

.SH LICENSE
See LICENSE for copyright information.
.SH SEE ALSO
cpt(1)
