.TH "cpt-update" "1" "2020-07-24" "CARBS LINUX" "General Commands Manual"
.SH NAME
cpt-update
.SH SYNOPSIS
\fBcpt-update\fR [options]

.SH OPTIONS
.TP
\fB--download\fR       Only download the updates
.TP
\fB--no-fetch\fR       Do not refresh the repositories
.TP
\fB--root\fR [rootdir] Use an alternate root directory
.PP

.SH DESCRIPTION
cpt-update checks for package updates.

.SH LICENSE
See LICENSE for copyright information.
.SH SEE ALSO
cpt(1)
