.Dd Feb 25, 2021
.Dt cpt-alternatives 1
.Sh NAME
.Nm cpt-alternatives
.Nd List and swap to alternatives
.Sh SYNOPSIS
.Nm cpt-alternatives
.Op Ar -
.Op Ar package file
.Sh USAGE
.Nm
can be used to either list or swap to alternatives, depending on the given
arguments:
.Bl -tag -offset indent -width 12n
.It Sy -
Swap to alternatives given on the standard input.
.It Sy none
List alternatives.
.It Sy pkg file
Swap to the alternative
.Sy file
from
.Sy pkg
.El
.Sh EXAMPLES
.Pp
Here are some sample commands to make it easier to understand how
.Nm
works.
.Ss LISTING ALTERNATIVES
.Pp
Calling
.Nm
without any arguments will print all available alternatives on your system.
.Bd -literal -offset indent
$ cpt-alternatives
ncurses /usr/bin/clear
ncurses /usr/bin/reset
.Ed
.Ss SWITCHING ALTERNATIVES
You can simply switch between alternatives by giving the name of the package and
the file as arguments.
.Bd -literal -offset indent
$ cpt-alternatives ncurses /usr/bin/clear
-> Swapping '/usr/bin/clear' from 'busybox' to 'ncurses'
.Ed
.Ss SWITCHING ALTERNATIVES IN BULK
There may be times where you want to change multiple alternatives at once. Here
is an example for using all alternatives from the package
.Sy sbase .
.Bd -literal -offset indent
$ cpt-alternatives | grep ^sbase | cpt-alternatives -
.Ed
.Sh AUTHOR
.An Cem Keylan Aq Mt cem@ckyln.com
.Sh LICENSE
See LICENSE for copyright information.
.Sh SEE ALSO
.Xr cpt 1
