.TH "cpt-build" "1" "2020-07-24" "CARBS LINUX" "General Commands Manual"
.SH NAME
cpt-build
.PP
.SH SYNOPSIS
\fBcpt-build\fR [pkg...]

.SH DESCRIPTION
cpt-build will build given packages and their dependencies. If multiple packages
are specified, it will ask to install the packages as well.

.SH LICENSE
See LICENSE for copyright information.
.SH SEE ALSO
cpt(1)
