.TH "cpt-list" "1" "2020-07-24" "CARBS LINUX" "General Commands Manual"
.SH NAME
cpt-list
.SH SYNOPSIS
\fBcpt-list\fR [pkg...]
.SH DESCRIPTION
cpt-list can be used to list all packages or check if the given package is
installed on the system.

.SH LICENSE
See LICENSE for copyright information.
.SH SEE ALSO
cpt(1)
