.Dd Feb 25, 2021
.Dt cpt-checksum 1
.Sh NAME
.Nm cpt-checksum
.Nd generate checksums
.Sh SYNOPSIS
.Nm
.Op Ar package...
.Sh DESCRIPTION
cpt-checksum lints a package, downloads the sources, and creates a checksum file
including the SHA256 digests of the sources.
.Sh AUTHOR
.An Cem Keylan Aq Mt cem@ckyln.com
.Sh LICENSE
See LICENSE for copyright information.
.Sh SEE ALSO
.Xr cpt 1
