.TH "cpt-checksum" "1" "2020-07-24" "CARBS LINUX" "General Commands Manual"
.SH NAME
cpt-checksum
.SH SYNOPSIS
\fBcpt-checksum\fR [pkg...]

.SH DESCRIPTION
cpt-checksum lints a package, downloads the sources, and creates a checksum file
including the SHA256 digests of the sources.

.SH LICENSE
See LICENSE for copyright information.
.SH SEE ALSO
cpt(1)
