.Dd Feb 25, 2021
.Dt cpt-remove 1
.Sh NAME
.Nm cpt-remove
.Nd remove given packages from the system
.Sh SYNOPSIS
.Nm
.Op Fl fy
.Op Fl -root Ar CPT_ROOT
.Op Ar package...
.Sh DESCRIPTION
.Nm
can be used to remove given packages from the system. If no arguments are
supplied,
.Nm
will assume that the current directory is the package.
.Pp
The options are as follows:
.Bl -tag -width 14n
.It Fl f , -force
Force removal
.It Fl y , -no-prompt
Do not prompt for confirmation
.It Fl -root Ar CPT_ROOT
Use an alternate root directory
.It Fl h , -help
Show help message
.It Fl v , -version
Print version information
.El
.Sh AUTHOR
.An Cem Keylan Aq Mt cem@ckyln.com
.Sh LICENSE
See LICENSE for copyright information.
.Sh SEE ALSO
.Xr cpt 1
.Xr cpt-install 1
