.Dd Feb 25, 2021
.Dt cpt 1
.Sh NAME
.Nm cpt
.Nd carbs packaging toolchain
.Sh SYNOPSIS
.Nm
.Op Ar extension arg...
.Sh DESCRIPTION
.Nm
is the packaging toolchain written for Carbs Linux. The base command
.Nm
will find and run the appropriate
.Em cpt-*
command based on the arguments.
.Pp
Each base tool have their own manual page and concise documentation can be found
on GNU info pages, either using the
.Xr info 1
program or through the web from
.Lk https://carbslinux.org/docs.html .
It can also be read plaintext by running
.Pp
.Dl less Pa /usr/share/doc/cpt.txt
.Sh AUTHOR
.An Cem Keylan Aq Mt cem@ckyln.com
.Sh LICENSE
See LICENSE for copyright information
.Sh SEE ALSO
.Xr cpt-build 1
.Xr cpt-install 1
