#!/bin/sh -ef
# Display all files owned by a package

## SYNOPSIS:
## .Nm
## .Op Ar package
## DESCRIPTION:
## .Nm
## prints the manifest of the given package to the standard output. If no
## package name is given,
## .Nm
## will use the name of the current directory for the package.

case "$1" in
    --help|-h)
        printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} [pkg]"
        exit 0
        ;;
    '') set -- "${PWD##*/}"
esac

cpt-list "$1" >/dev/null
cat "$CPT_ROOT/var/db/cpt/installed/$1/manifest" 2>/dev/null
