#!/bin/sh -e
# Check which package owns a file

# Source the package manager library.
# shellcheck disable=1091
. cpt-lib

case "$1" in ''|--help|-h) out "usage: ${0##*/} [file]"; exit 0; esac

# If full path is not specified, use either the current directory, or look for a
# command.
case "$1" in
    /*) ;;
     *)
        if [ -f "$1" ]; then
            set -- "$PWD/$1"
        else
            set -- "$(command -v "$1")"
        fi
esac

# Strip 'CPT_ROOT' from the file path if passed and follow symlinks.
file="${1#$CPT_ROOT}"
dirname=$(_readlinkf "$CPT_ROOT/${file%/*}")
file="$dirname/${file##*/}"

# Check if the file exists and exit if it is not.
[ -f "$file" ] || {
    [ -d "$file" ] && die "please specify a file instead of a directory"
    die "file '$1' doesn't exist."
}

pkg_owner -lFx "$file" || die "Cannot determine which package owns '$file'"
