#!/bin/sh -ef
# Display all files owned by a package
case "$1" in ''|--help|-h) printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} [pkg]" ; exit 0 ; esac

kiss l "$1" >/dev/null
cat "$KISS_ROOT/var/db/kiss/installed/$1/manifest" 2>/dev/null
