#!/bin/sh -e
# Display packages which depend on package

case "$1" in
    --help|-h)
        printf '%s\n' "usage: ${0##*/} [pkg]"
        exit 0
        ;;
    '') set -- "${PWD##*/}"
esac

# 'cd' to the database directory as a simple way of
# stripping the path and performing a 'basename'.
cd "$CPT_ROOT/var/db/cpt/installed"

# Use a simple 'grep' to display packages depending on '$1'.
grep "^$1\$" -- */depends
