#!/bin/sh -e
# Concatanate package files in the installed package database
# File names are printed to stderr.
case "$1" in
    --help|-h)
        printf '\033[1;33m-> \033[musage: %s [pkg] [file...]\n' "${0##*/}"
        exit 0
        ;;
    '')
        set -- "${PWD##*/}"
esac

cpt-list "${pkg:=$1}" >/dev/null ; shift

for file in ${*:-build depends sources version} ; do
    [ -f "/var/db/cpt/installed/$pkg/$file" ] && {
        printf '\033[1m%s:\033[m\n' "$file" >&2
        cat "/var/db/cpt/installed/$pkg/$file"
    }
done
