#!/bin/sh -ef
# Turn an installed package into a CPT tarball

case "$1" in
    --help|-h)
        printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} [pkg]"
        exit 0
        ;;
    '') set -- "${PWD##*/}"
esac

cpt-list "${1:-null}" >/dev/null

# Grab the package's version..
read -r ver rel 2>/dev/null < \
    "$CPT_ROOT/var/db/cpt/installed/$1/version"

# Reset the argument list.
pkg=$1
set --

# Construct the argument list using each file.
while read -r file; do
    [ -d "$CPT_ROOT/$file" ] || set -- "$@" ".$file"
done < "$CPT_ROOT/var/db/cpt/installed/$pkg/manifest"

# Turn the list of files back into a package.
: "${CPT_COMPRESS:=gz}"
tar cf - -C / -- "$@" | case "$CPT_COMPRESS" in
    bz2) bzip2 -z ;;
    gz)  gzip -6  ;;
    xz)  xz -zT 0 ;;
    zst) zstd -3  ;;
    *)   gzip -6  ;;  # Fallback to gzip
esac > "$pkg#$ver-$rel.tar.$CPT_COMPRESS"

printf 'tarball created in %s\n' "$PWD/$pkg#$ver-$rel.tar.$CPT_COMPRESS"
