#!/bin/sh -e
# Display a package's dependencies in the repository

case "$1" in
    --help|-h)
        printf '%s\n' "usage: ${0##*/} [pkg]"
        exit 0
        ;;
    '') set -- "${PWD##*/}"
esac

cpt-search "$1" >/dev/null
cat "$(cpt-search --single "$1")/depends" 2>/dev/null
