#!/bin/sh -ef
# Fork a package to the current directory

case "$1" in ''|--help|-h) printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} [pkg]" ; exit 0 ; esac
[ "$CPT_FORCE" ] || {
    [ -d "$1" ] && {
        printf '\033[1;31m!> \033[m%s\n' "$1 already exists on the current directory" \
               "You can set CPT_FORCE=1 to ignore this."
        exit 1
    }
}

cpt-search "$1" >/dev/null

cp -r "$(cpt-search --single "$1")" .
printf 'forked package to %s\n' "$PWD/$1"
