#!/bin/sh -ef
# Display a package's dependencies

case "$1" in
    --help|-h)
        printf 'usage: %s [pkg]\n' "${0##*/}"
        exit 0
        ;;
    '') set -- "${PWD##*/}"
esac

cpt-list "$1" >/dev/null
cat "$CPT_ROOT/var/db/cpt/installed/$1/depends" 2>/dev/null ||:
