#!/bin/sh -ef
# Display all files owned by a package with a tree view

case "$1" in
    --help|-h)
        printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} [pkg]"
        exit 0
        ;;
    '') set -- "${PWD##*/}"
esac
cpt-list "$1" >/dev/null
printf '%s\n' "[$1]:"
tree -C --fromfile "$CPT_ROOT/var/db/cpt/installed/$1/manifest" | sed 1,2d
