#!/bin/sh -ef

[ "$1" ] || { printf 'usage: kiss-link [file] [file]\n' ; exit 0 ;}

# Check if the package exists in a repository and error out here
# if it does not. The error message from the package manager will
# be displayed.
kiss s "${PKG:=${PWD##*/}}" >/dev/null

oPKG="$(kiss s "$PKG" | grep -v "^$PWD\$\|/var/db/kiss/installed/$PKG" | sed 1q)"

for file in "$@" ; do
    [ -e "${oPKG:?}/$file" ]
    ln -sf "$oPKG/$file" "$file"
    printf 'linked %s to %s\n' "$oPKG/$file" "$PWD/$file"
done
