#!/bin/sh -e
# Display a package's dependencies in the repository

[ "$1" ] || { printf '%s\n' "usage: kiss-repodepends <pkg>" ; exit 1 ;}
kiss s "$1" >/dev/null

cat "$(kiss s "$1" | sed 1q)/depends" 2>/dev/null
