#!/bin/sh -e
# Print the git log of the specific package

case "$1" in ''|--help|-h) printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} [pkg]"; exit 0; esac

kiss s "$1" >/dev/null
cd "$(kiss s "$1" | sed 1q)"

# Pipe to cat so it doesn't automatically paged
# by git.
git log --format='<%as> [%an] %s - %h' . | cat
