#!/bin/sh -e
# Check which package owns a file

case "$1" in ''|--help|-h) printf '%s\n' "usage: kiss-owns <file>" ; exit 0 ; esac

# Strip 'KISS_ROOT' from the file path if passed and
# follow symlinks.
file="${1#$KISS_ROOT}"
dirname=$(kiss-readlink "$KISS_ROOT/{$file%/*}")
file="$dirname/${file##*/}"

# Check if the file exists and exit if it is not.
[ -f "$file" ] || {
    [ -d "$file" ] && printf '%s\n' \
        "error: please specify a file instead of a directory" >&2 ||
        printf '%s\n' "error: file '$1' doesn't exist." >&2
    exit 1
}

# Print the full path to the manifest file which contains
# the match to our search.
pkg_owns=$(grep -lFx "${file#$KISS_ROOT}" \
                     "$KISS_ROOT/var/db/kiss/installed/"*/manifest)


# Extract the package name from the path above.
pkg_owns=${pkg_owns%/*}
pkg_owns=${pkg_owns##*/}

printf '%s\n' "[$pkg_owns] owns '$1'"
