#!/bin/sh -e
# Create a boilerplate KISS package

out() { printf '\033[1;33m-> \033[m%s\n' "$@" >&2 ;}
die() { printf '\033[1;31m!> \033[m%s\n' "$@" >&2 ; exit 1 ;}

[ "$1" ] || {
    out "usage: ${0##*/} <name> [version] [source]" \
        "Create boilerplate kiss packages"
    exit 0
}

[ -d "$1" ] && die "Package '$1' already exists."

# Create the directory
mkdir -p "$1"

# Create the build file
printf '%s\n' "#!/bin/sh -e" > "$1/build" ; chmod +x "$1/build"

# Create the version file
printf '%s\n' "$2 1" > "$1/version"

# Create the sources file
printf '%s\n' "$3" > "$1/sources"

out "Package '$1' created to '$PWD/$1'"
