#!/bin/sh -ef
# Show the size on disk for a package

[ "$1" ] || { printf '%s\n' "usage: kiss-size <pkg>" ; exit 1 ;}
kiss s "$1" >/dev/null

# Filter directories from manifest and leave only files.
# Directories in the manifest end in a trailing '/'.
files=$(sed 's|.*/$||' "$KISS_ROOT/var/db/kiss/installed/$1/manifest")

# Send the file list to 'du'.
# This unquoted variable is safe as word splitting is intended
# and globbing is globally disabled in this script.
# shellcheck disable=2086
du -shc -- $files 2>/dev/null
