#!/bin/sh
# Create static cargo sources for Rust packages
case "$1" in ''|--help|-h) printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} [crate+ver] [crate+ver]"; exit 0 ; esac

# We convert the name-version seperator from '+' to '-' to
# avoid issues that may arise from version numbers that include
# a '-'.

for crate in "$@"; do
    printf 'https://static.crates.io/crates/%s/%s.crate vendor\n' \
        "${crate%+*}" "$(echo "$crate" | sed 's/+/-/')"
done
