#!/bin/sh -ef
# Display a package's dependencies

[ "$1" ] || { printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} <pkg>" ; exit 0 ;}

kiss l "$1" >/dev/null
cat "$KISS_ROOT/var/db/kiss/installed/$1/depends" 2>/dev/null
