#!/bin/sh -ef
# Find the maintainer of a package

case "$1" in ''|--help|-h) printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} <pkg>" ; exit 0 ; esac

kiss s "$1" | while read -r repo; do cd "$repo"
    m=$(git log -1 version 2>/dev/null) ||:
    m=${m##*Author: }
    m=${m%%>*}

    [ "$m" ] || continue

    printf '=> %s\n%s>\n' "$PWD" "$m"
done
