#!/bin/sh -e
#
# kiss-orphans - List orphaned packages.

cd "$KISS_ROOT/var/db/kiss/installed/"

for pkg in *; do
    case $pkg in
        baseinit|baselayout|gcc|pkgconf|e2fsprogs|musl|\
        make|busybox|bzip2|grub|kiss|git|linux-headers)
            continue
    esac

    grep -q "^$pkg$" ./*/depends || printf '%s\n' "$pkg"
done

printf '\033[1;33m-> \033[m%s\n' "kiss-orphans: lists packages that do not" \
       "have any packages depending on them" >&2
