#!/bin/sh -e
# Locate the first instance of a KISS package

case "$1" in ''|--help|-h) printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} [pkg]" ; exit 0; esac

{ kiss s "$1" || exit 1 ;} |
    sed 1q
