#!/bin/sh -ef
#
# kiss-manifest-tree - Display all files owned by a package.

[ "$1" ] || { printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} <pkg>" ; exit 0 ;}
kiss l "$1" >/dev/null
printf '%s\n' "[$1]:"
tree -C --fromfile "$KISS_ROOT/var/db/kiss/installed/$1/manifest" | sed 1,2d
