#!/bin/sh -e

# Print the git log of the specific package

[ "$1" ] || {
    printf '\033[1;33m-> \033[musage: %s [pkg]\n' "${0##*/}"
    exit 0
}

kiss s "$1" >/dev/null
cd "$(kiss s "$1" | sed 1q)"

# Pipe to cat so it doesn't automatically paged
# by git.
git log --format='<%as> [%an] %s - %h' . | cat
