image: alpine/edge
packages:
  - musl-dev
  - gcc
  - bison
  - curl
  - rsync
  - shellcheck
  - texinfo
  - gzip
tasks:
  - build: |
      cd cpt
      make
  - install-pax: |
      git clone https://github.com/carbslinux/otools
      cd otools
      make pax
      sudo install -Dm755 pax /usr/bin/pax
  - test: |
      cd cpt
      curl -fsSL https://git.io/shellspec | sudo sh -s -- -y -p /usr
      make test
triggers:
  - action: email
    condition: failure
    to: cem@carbslinux.org
