image: alpine/edge
packages:
  - musl-dev
  - gcc
  - bison
  - curl
  - rsync
  - emacs-nox
  - texinfo
  - gzip
  - xz
tasks:
  - install-pax: |
      git clone --quiet https://github.com/carbslinux/otools
      cd otools
      ./configure
      make pax
      sudo install -Dm755 pax /usr/bin/pax
  - install-blake3: |
      git clone --quiet https://git.sr.ht/~mcf/b3sum
      cd b3sum
      sudo make PREFIX=/usr install
  - install-shellspec: |
      curl -fsSL https://git.io/shellspec | sudo sh -s -- -y -p /usr
  - install-shellcheck: |
      curl -fsLo- https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz | pax -Jr
      sudo install -Dm755 shellcheck-v0.8.0/shellcheck /usr/bin/shellcheck
  - build: |
      cd cpt
      ./configure
      make
  - test: |
      cd cpt
      make test
triggers:
  - action: email
    condition: failure
    to: cem@carbslinux.org
