image: alpine/edge
packages:
  - curl
  - shellcheck
  - texinfo
tasks:
  - build: |
      cd cpt
      make
  - test: |
      cd cpt
      curl -fsSL https://git.io/shellspec | sudo sh -s -- 0.27.2 -y -p /usr
      make test
