image: alpine/edge
packages:
  - musl-dev
  - gcc
  - bison
  - curl
  - rsync
  - shellcheck
  - texinfo
  - gzip
tasks:
  - install-pax: |
      git clone --quiet https://github.com/carbslinux/otools
      cd otools
      ./configure
      make pax
      sudo install -Dm755 pax /usr/bin/pax
  - install-blake3: |
      git clone --quiet https://git.sr.ht/~mcf/b3sum
      cd b3sum
      sudo make PREFIX=/usr install
  - build: |
      cd cpt
      ./configure
      make
  - test: |
      cd cpt
      curl -fsSL https://git.io/shellspec | sudo sh -s -- -y -p /usr
      make test
triggers:
  - action: email
    condition: failure
    to: cem@carbslinux.org
