image: alpine/edge
packages:
  - curl
  - rsync
  - shellcheck
  - texinfo
  - gzip
tasks:
  - build: |
      cd cpt
      make
  - test: |
      cd cpt
      curl -fsSL https://git.io/shellspec | sudo sh -s -- -y -p /usr
      make test
triggers:
  - action: email
    condition: failure
    to: cem@carbslinux.org
