#!/bin/sh -ef
# List installed packages

# shellcheck disable=1091
if command -v cpt-lib >/dev/null; then . cpt-lib; else . ../lib.sh; fi

case "$1" in
    --help|-h) out "usage: ${0##*/} [pkg...]"; exit 1 ;;
    --version|-v) version ;;
esac

pkg_list "$@"
