#!/bin/sh -ef
# Search for a package

# shellcheck disable=1091
if command -v cpt-lib >/dev/null; then . cpt-lib; else . ./cpt-lib; fi

# By default we are showing all instances of a package. This value can be unset
# in order to only find the first instance of a package.
all=1

case "$1" in
    --help|-h|'')
        out "usage: ${0##*/} [--single] [pkg...]" "" \
            "  Options:" \
            "    --single  Only show the first instance of a package" ""
        exit 0
        ;;
    --version|-v) version ;;
    --single) unset all; shift ;;
esac

for pkg; do pkg_find "$pkg" "${all:+all}"; done
