#!/bin/sh -ef
# Download sources for the given package

if [ -f ./cpt-lib ]; then . ./cpt-lib; else . cpt-lib; fi

case "$1" in
    --help|-h)
        out "usage: ${0##*/} [pkg...]"
        exit 1
        ;;
    --version|-v) version ;;
    '') set -- "${PWD##*/}"; export CPT_PATH=${PWD%/*}:$CPT_PATH
esac

create_cache
for pkg; do pkg_sources "$pkg"; done
