#!/bin/sh
# Install a package

parser_definition() {
    setup REST help:usage -- "usage: ${0##*/} [pkg...]"
    msg -- '' 'Options:'
    flag  CPT_FORCE -f --force init:@export -- "Force installation"
    global_options
}

if [ -f ./cpt-lib ]; then . ./cpt-lib; else . cpt-lib; fi

[ "$1" ] || set -- "${PWD##*/}"; export CPT_PATH=${PWD%/*}:$CPT_PATH

[ -w "$CPT_ROOT/" ] || [ "$uid" = 0 ] || {
    as_root "$0" "$@"
    exit $?
}

pkg_order "$@"

create_cache

# shellcheck disable=2154
for pkg in $order; do pkg_install "$pkg"; done

# After installation is complete, show a list of messages from packages.
log "Retrieving post-installation message queue"
unset msg

for pkg in $order; do
    [ -f "$sys_db/$pkg/message" ] && {
        printf '%s\n%s\n%s\n\n' \
               "=======================================" \
               "$pkg" \
               "======================================="
        cat "$sys_db/$pkg/message" >&2
        msg=1
    }
done
[ "$msg" ] || log "No message in queue"
