#!/bin/sh -ef
# Check for updates

# shellcheck disable=1091
if command -v cpt-lib >/dev/null; then . cpt-lib; else . ./cpt-lib; fi

parser_definition() {
    setup REST -- "usage: ${0##*/} [options]"
    msg -- '' 'Options:'
    flag  download_only -d --download                           -- "Only download updatable packages"
    flag  CPT_FETCH     -n --no-fetch  on:0  init:"$CPT_FETCH"  -- "Do not refresh the repositories"
    flag  CPT_PROMPT    -y --no-prompt on:0  init:"$CPT_PROMPT" -- "Do not prompt for confirmation"
    param CPT_ROOT         --root            init:"$CPT_ROOT"   -- "Use an alternate root directory"
    disp  :usage        -h --help                               -- "Show this help message"
    disp  :version      -v --version                            -- "Print version information"
}

eval "$(getoptions      parser_definition parse "$0")"
eval "$(getoptions_help parser_definition usage "$0")"

parse "$@"
eval set -- "$REST"

create_cache

pkg_updates
