#!/bin/sh -ef
# List installed packages

parser_definition() {
    setup REST help:usage -- \
        "usage: ${0##*/} [-cq] pkg..." \
        "or:    ${0##*/} -C pkg true-statement false-statement"
    msg -- '' 'Options:'
    flag CURRENT -c --current -- "Use the current directory as a package"
    flag quiet   -q --quiet   -- "Make the operation quiet"
    param PKG    -C --check label:"    -C,--check PKG TRUE FALSE" -- \
          "Check if PKG exists and return the string of TRUE if"\
          "it exists, and the string of FALSE if it doesn't." \
          "Useful for optional packaging."
    global_options
}

if [ -f ./cpt-lib ]; then . ./cpt-lib; else . cpt-lib; fi

if [ "$PKG" ]; then
    if pkg_list "$PKG" >/dev/null 2>&1; then
        printf %s "$1"
    else
        printf %s "$2"
    fi
else
    [ "$CURRENT" ] && set -- "${PWD##*/}"
    [ "$quiet" ]   && exec >/dev/null 2>&1
    pkg_list "$@"
fi
