#!/bin/sh -ef
# Remove a package

# shellcheck disable=1091
if command -v cpt-lib >/dev/null; then . cpt-lib; else . ./cpt-lib; fi

parser_definition() {
    setup REST -- "usage: ${0##*/} [pkg...]"
    msg -- '' 'Options:'
    flag  CPT_FORCE -f --force init:"$CPT_FORCE"  -- "Force removal"
    param CPT_ROOT     --root  init:"$CPT_ROOT"   -- "Use an alternate root directory"
    disp  :usage    -h --help                     -- "Show this help message"
    disp  :version  -v --version                  -- "Print version information"
}

eval "$(getoptions      parser_definition parse "$0")"
eval "$(getoptions_help parser_definition usage "$0")"

parse "$@"
eval set -- "$REST"

[ "$1" ] || set -- "${PWD##*/}"; export CPT_PATH=${PWD%/*}:$CPT_PATH

[ -w "$CPT_ROOT/" ] || [ "$uid" = 0 ] || {
    as_root "$0" "$@"
    exit $?
}

create_cache

pkg_order "$@"
for pkg in $redro; do pkg_remove "$pkg" "${CPT_FORCE:-check}"; done
