#!/bin/sh
# Build a package

# shellcheck disable=1091
if command -v cpt-lib >/dev/null; then . cpt-lib; else . ./cpt-lib; fi

case "$1" in
    '') set -- "${PWD##*/}"; export CPT_PATH=${PWD%/*}:$CPT_PATH ;;
    --help|-h) out "usage: ${0##*/} [pkg...]"; exit 1 ;;
    --version|-v) version ;;
esac

create_cache

pkg_build "$@"
