#!/bin/sh
# Build a package

if [ -f ./cpt-lib ]; then . ./cpt-lib; else . cpt-lib; fi

parser_definition() {
    setup REST -- "usage: ${0##*/} [pkg...]"
    msg -- '' 'Options:'
    flag CPT_TEST   -t --test                init:="$CPT_TEST"    -- "Run tests (if it exists)"
    global_options
}

eval "$(getoptions      parser_definition parse "$0")"
eval "$(getoptions_help parser_definition usage "$0")"

parse "$@"
eval set -- "$REST"

[ "$1" ] || set -- "${PWD##*/}"; export CPT_PATH=${PWD%/*}:$CPT_PATH

create_cache

pkg_build "$@"
