#!/bin/sh -ef
# Generate checksums

if [ -f ./cpt-lib ]; then . ./cpt-lib; else . cpt-lib; fi

case "$1" in
    --help|-h) out "usage: ${0##*/} [pkg...]"; exit 1 ;;
    --version|-v) version ;;
    '') set -- "${PWD##*/}"; export CPT_PATH=${PWD%/*}:$CPT_PATH ;;
esac

create_cache

for pkg; do pkg_lint    "$pkg" c; done
for pkg; do pkg_sources "$pkg" c; done

for pkg; do
    pkg_checksums "$pkg" | {
        repo_dir=$(pkg_find "$pkg")

        if [ -w "$repo_dir" ]; then
            tee "$repo_dir/checksums"
        else
            log "$pkg" "Need permissions to generate checksums"

            user=$(cpt-stat "$repo_dir") as_root tee "$repo_dir/checksums"
        fi
    }

    log "$pkg" "Generated checksums"
done
