#!/bin/sh -ef
# Search for a package

if [ -f ./cpt-lib ]; then . ./cpt-lib; else . cpt-lib; fi

parser_definition() {
    setup REST -- "usage: ${0##*/} [pkg...]"
    msg -- '' 'Options:'
    flag all      -s --single init:=1 on:'' -- "Only show the first instance of a package"
    disp :usage   -h --help                     -- "Show this help message"
    disp :version -v --version                  -- "Print version information"
}

eval "$(getoptions      parser_definition parse "$0")"
eval "$(getoptions_help parser_definition usage "$0")"

parse "$@"
eval set -- "$REST"

for pkg; do pkg_find "$pkg" "${all:+all}"; done
