#!/bin/sh -ef
# Fetch repositories

# shellcheck disable=1091
if command -v cpt-lib >/dev/null; then . cpt-lib; else . ./cpt-lib; fi

case "$1" in
    --help|-h) out "usage: ${0##*/}"; exit 1 ;;
    --version|-v) version ;;
esac

pkg_fetch
