#!/bin/sh -ef
# Remove a package

# shellcheck disable=1091
if command -v cpt-lib >/dev/null; then . cpt-lib; else . ./cpt-lib; fi

eval set -- "$(getopt -l help,version,force,root: -- fhv "$@")"
while :; do
    case "$1" in
        --help|-h)
            out "usage: ${0##*/} [options] [pkg...]" "" \
                "  Options:" \
                "    --force           Force Removal" \
                "    --root [rootdir]  Use an alternate root directory" ""
            exit 1
            ;;
        -v|--version) version ;;
        -f|--force) export CPT_FORCE=1; shift   ;;
        --root)  export CPT_ROOT=$2; shift 2 ;;
        --) shift; break ;;
    esac
done

[ "$1" ] || set -- "${PWD##*/}"; export CPT_PATH=${PWD%/*}:$CPT_PATH

[ -w "$CPT_ROOT/" ] || [ "$uid" = 0 ] || {
    as_root "$0" "$@"
    exit $?
}

pkg_order "$@"
for pkg in $redro; do pkg_remove "$pkg" "${CPT_FORCE:-check}"; done
