#!/bin/sh -ef
# Search for a package

if [ -f ./cpt-lib ]; then . ./cpt-lib; else . cpt-lib; fi

parser_definition() {
    setup REST help:usage -- "usage: ${0##*/} [pkg...]"
    msg -- '' 'Options:'
    flag all    -s --single init:=1 on:'' -- "Only show the first instance of a package"
    global_options
}

eval "$(getoptions parser_definition parse "$0")"

parse "$@"
eval set -- "$REST"

# The 'all' variable is set by the option parser.
# shellcheck disable=2154
for pkg; do pkg_find "$pkg" "${all:+all}"; done
