name: test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run tests.
        run: |
          wget https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz
          xz -cd shellcheck-v0.7.1.linux.x86_64.tar.xz | tar xf -
          export PATH=shellcheck-v0.7.1:$PATH
          make test
