name: main
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run make
        run: make
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Install shellspec
        run: curl -fsSL https://git.io/shellspec | sudo sh -s -- -p /usr/local -y
      - name: Run tests
        run: make test
